---
- block :
    - name: stopped service firewalld
      systemd:
        name: firewalld
        enabled: no
        state: stopped

    - name: Enable IPV4 forwarding
      lineinfile:
        path: /etc/sysctl.conf
        line: "{{ item }}"
      register: sysctl
      with_items:
        - 'net.bridge.bridge-nf-call-ip6tables = 1'
        - 'net.bridge.bridge-nf-call-iptables = 1'
        - 'net.ipv4.ip_forward = 1'
        - 'net.ipv6.conf.all.disable_ipv6 = 1'
        - 'net.ipv6.conf.default.disable_ipv6 = 1'
        - 'vm.overcommit_memory=1'
        - 'vm.panic_on_oom=0'
        - 'kernel.panic=10'
        - 'kernel.panic_on_oops=1'
        - 'kernel.keys.root_maxkeys=1000000'
        - 'kernel.keys.root_maxbytes=25000000'

    - name: Reload forwarding rules
      command:
        cmd: sysctl --system
      when: sysctl is changed